"""Dashboard copy of the curated SEC watchlist.

The dashboard is deployed from the serving/dashboard build context, so it keeps
a small static copy of ticker-to-company names for search/autocomplete.
CIKs live in config/watchlist.py and remain the ingestion source of truth.
"""

from __future__ import annotations


WATCHLIST_COMPANY_NAMES: dict[str, str] = {
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corp",
    "NVDA": "NVIDIA Corp",
    "TSLA": "Tesla, Inc.",
    "GOOGL": "Alphabet Inc.",
    "AMZN": "Amazon.com, Inc.",
    "META": "Meta Platforms, Inc.",
    "JPM": "JPMorgan Chase & Co.",
    "GS": "Goldman Sachs Group Inc.",
    "NFLX": "Netflix Inc.",
    "BRK-B": "Berkshire Hathaway Inc.",
    "V": "Visa Inc.",
    "MA": "Mastercard Inc.",
    "UNH": "UnitedHealth Group Inc.",
    "HD": "Home Depot, Inc.",
    "PG": "Procter & Gamble Co.",
    "JNJ": "Johnson & Johnson",
    "ABBV": "AbbVie Inc.",
    "MRK": "Merck & Co., Inc.",
    "PFE": "Pfizer Inc.",
    "KO": "Coca-Cola Co.",
    "PEP": "PepsiCo Inc.",
    "WMT": "Walmart Inc.",
    "COST": "Costco Wholesale Corp",
    "TGT": "Target Corp",
    "BAC": "Bank of America Corp",
    "WFC": "Wells Fargo & Co.",
    "C": "Citigroup Inc.",
    "MS": "Morgan Stanley",
    "BLK": "BlackRock, Inc.",
    "ORCL": "Oracle Corp",
    "CRM": "Salesforce, Inc.",
    "ADBE": "Adobe Inc.",
    "AMD": "Advanced Micro Devices Inc.",
    "INTC": "Intel Corp",
    "QCOM": "Qualcomm Inc.",
    "TXN": "Texas Instruments Inc.",
    "NOW": "ServiceNow, Inc.",
    "SNOW": "Snowflake Inc.",
    "UBER": "Uber Technologies, Inc.",
    "LYFT": "Lyft, Inc.",
    "SHOP": "Shopify Inc.",
    "XYZ": "Block, Inc.",
    "PYPL": "PayPal Holdings, Inc.",
    "COIN": "Coinbase Global, Inc.",
    "SPOT": "Spotify Technology S.A.",
    "DIS": "Walt Disney Co.",
    "CMCSA": "Comcast Corp",
    "T": "AT&T Inc.",
    "NKE": "Nike, Inc.",
    "AVGO": "Broadcom Inc.",
    "MU": "Micron Technology Inc.",
    "LLY": "Eli Lilly & Co.",
    "XOM": "ExxonMobil Holdings Corp",
    "ASML": "ASML Holding NV",
    "PLTR": "Palantir Technologies Inc.",
    "CSCO": "Cisco Systems, Inc.",
    "CVX": "Chevron Corp",
    "CAT": "Caterpillar Inc.",
    "HSBC": "HSBC Holdings PLC",
    "LRCX": "Lam Research Corp",
    "AMAT": "Applied Materials Inc.",
    "GE": "General Electric Co.",
    "DELL": "Dell Technologies Inc.",
    "NVS": "Novartis AG",
    "RY": "Royal Bank of Canada",
    "PM": "Philip Morris International Inc.",
    "BABA": "Alibaba Group Holding Ltd",
    "MUFG": "Mitsubishi UFJ Financial Group Inc.",
    "RTX": "RTX Corp",
    "PANW": "Palo Alto Networks Inc.",
    "ARM": "ARM Holdings PLC",
    "AZN": "AstraZeneca PLC",
    "SHEL": "Shell plc",
    "GEV": "GE Vernova Inc.",
    "SAP": "SAP SE",
    "ANET": "Arista Networks, Inc.",
    "AMGN": "Amgen Inc.",
    "TM": "Toyota Motor Corp",
    "BHP": "BHP Group Ltd",
    "TMO": "Thermo Fisher Scientific Inc.",
    "KLAC": "KLA Corp",
    "AXP": "American Express Co.",
    "LIN": "Linde plc",
    "IBM": "International Business Machines Corp",
    "CRWD": "CrowdStrike Holdings, Inc.",
    "SAN": "Banco Santander, S.A.",
    "VZ": "Verizon Communications Inc.",
    "NVO": "Novo Nordisk A/S",
    "RTNTF": "Rio Tinto Ltd",
    "TMUS": "T-Mobile US, Inc.",
    "TD": "Toronto-Dominion Bank",
    "APH": "Amphenol Corp",
    "TTE": "TotalEnergies SE",
    "SCHW": "Charles Schwab Corp",
    "MRVL": "Marvell Technology, Inc.",
    "ABT": "Abbott Laboratories",
    "GILD": "Gilead Sciences, Inc.",
    "DE": "Deere & Co.",
    "MCD": "McDonald's Corp",
    "STX": "Seagate Technology Holdings plc",
    "NEE": "NextEra Energy Inc.",
    "SMFG": "Sumitomo Mitsui Financial Group, Inc.",
    "WELL": "Welltower Inc.",
    "UNP": "Union Pacific Corp",
    "ADI": "Analog Devices Inc.",
    "UBS": "UBS Group AG",
    "SCCO": "Southern Copper Corp",
    "RIO": "Rio Tinto PLC",
    "BA": "Boeing Co.",
    "BX": "Blackstone Inc.",
    "COP": "ConocoPhillips",
    "BBVA": "Banco Bilbao Vizcaya Argentaria, S.A.",
    "DTEGY": "Deutsche Telekom AG",
    "WDC": "Western Digital Corp",
    "IBKR": "Interactive Brokers Group, Inc.",
    "BUD": "Anheuser-Busch InBev SA/NV",
    "HTHIY": "Hitachi Ltd",
    "ETN": "Eaton Corp plc",
    "ATEYY": "Advantest Corp",
    "DHR": "Danaher Corp",
    "BKNG": "Booking Holdings Inc.",
    "SONY": "Sony Group Corp",
    "TJX": "TJX Companies Inc.",
    "SMERY": "Siemens Energy AG",
    "VRTX": "Vertex Pharmaceuticals Inc.",
    "BMY": "Bristol Myers Squibb Co.",
    "UL": "Unilever PLC",
    "NEM": "Newmont Corp",
    "MFG": "Mizuho Financial Group Inc.",
    "COF": "Capital One Financial Corp",
    "CB": "Chubb Ltd",
    "PLD": "Prologis, Inc.",
    "ISRG": "Intuitive Surgical Inc.",
    "PBR": "Petrobras",
    "SPGI": "S&P Global Inc.",
    "PGR": "Progressive Corp",
    "GLW": "Corning Inc.",
    "CVS": "CVS Health Corp",
    "BMO": "Bank of Montreal",
    "LMT": "Lockheed Martin Corp",
    "SBUX": "Starbucks Corp",
    "PH": "Parker-Hannifin Corp",
    "BTI": "British American Tobacco p.l.c.",
    "HDB": "HDFC Bank Ltd",
    "ACN": "Accenture plc",
    "MDT": "Medtronic plc",
    "SYK": "Stryker Corp",
    "MO": "Altria Group, Inc.",
    "PDD": "PDD Holdings Inc.",
}
